version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_ROOT_DATABASE: $MONGO_DATABASE
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis
    restart: always
    env_file:
      - .env
    ports:
      - $REDIS_PORT:$REDIS_PORT
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - app-network
    volumes:
    # Copy source code to container 
      - .:/usr/src/app
    # Can not override node modules in container
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge